#!/bin/bash
#SBATCH -N 1     
#SBATCH -c 8
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:15:00                  
#SBATCH --gres=gpu:V100:2
#SBATCH --mem-per-gpu=32G
#SBATCH -J test-job-oc    # jobs name
#SBATCH -o ./slurm_outs/slurm_%j.out   # file to write logs, prints, etc

pwd
module purge
module load anaconda3
module load cuda
module load pytorch

# And then some code to run, like
python3 experiments.py